#!/bin/sh

cpu_temp="$(cat /sys/devices/virtual/thermal/thermal_zone0/temp)"
wifi0_temp="$(cat /sys/class/net/wifi0/thermal/temp)"
wifi1_temp="$(cat /sys/class/net/wifi1/thermal/temp)"

echo -n "CPU: ${cpu_temp}°C, WiFi: ${wifi0_temp}°C, ${wifi1_temp}°C"
